Lab8
Whigra1/labs pull request #5
Opened 2018-11-29 20:35 UTC by Whigra1

2018-11-29 20:35 UTC, Whigra1 commented
@nechaido

2018-12-13 18:35 UTC, nechaido requested changes
Декомпозировать.

2018-12-13 18:46 UTC, Whigra1 commented
Исправил

2018-12-13 20:11 UTC, nechaido approved these changes
Принято.

2018-12-14 19:22 UTC, closed without merging